sonar.projectKey=devsecops-nodejs-app
sonar.projectName=devsecops-nodejs-app

sonar.sources=.
sonar.tests=test

sonar.test.inclusions=test/**/*.js

sonar.exclusions=node_modules/**,coverage/**,test/**
