apiVersion: apps/v1
kind: Deployment
metadata:
  name: devsecops-nodejs-app
spec:
  replicas: 4
  selector:
    matchLabels:
      app: devsecops-nodejs-app
  template:
    metadata:
      labels:
        app: devsecops-nodejs-app
    spec:
      containers:
        - name: devsecops-nodejs-app
          image: amol20/devsecops-nodejs-app:latest
          ports:
            - containerPort: 3000
